#!/bin/sh
#
# Copyright (c) 2014 Tristan Le Guern <tleguern@bouledef.eu>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

set -e

echo "XPM.prototype.X11NameToHex = {"

cat rgb.txt | grep -v '^!' | tr '\t' ' ' | while read; do
	name=`echo $REPLY | cut -d ' ' -f4-`
	red=`echo $REPLY | cut -d ' ' -f1`
	green=`echo $REPLY | cut -d ' ' -f2`
	blue=`echo $REPLY | cut -d ' ' -f3`
	echo "\t'$name': 'rgba($red, $green, $blue, 1)',"
done

echo "};"
